### ISSUE TITLE
Failed to activate the command-logger package

### ISSUE THREAD

**Issue by klynton** [kevinsawicki/command-logger#8]
[Enter steps to reproduce below:]
1. I upgraded to 0.190.0.
2. I re-opened Atom.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [command-logger](https://github.com/kevinsawicki/command-logger) package, v0.22.0
### Stack Trace

Failed to activate the command-logger package

```
At Cannot read property 'onDidMatchBinding' of undefined

TypeError: Cannot read property 'onDidMatchBinding' of undefined
    at Object.module.exports.activate (/Users/klynton/Dropbox/Apps/Atom/packages/command-logger/lib/main.coffee:68:46)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      "*.un~"
    ],
    "disabledPackages": [
      "autocomplete",
      "remember-session",
      "pain-split",
      "vim-mode",
      "atom-lint"
    ],
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ],
    "projectHome": "/Users/klynton/src",
    "audioBeep": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-django, v0.2.1
atom-erb, v0.1.0
atom-runner, v2.3.0
autocomplete-clang, v0.6.4
autocomplete-plus, v2.9.0
autoflow-diffable, v0.3.1
color-picker, v1.6.0
command-logger, v0.22.0
django-templates, v0.4.0
editor-stats, v0.17.0
git-plus, v4.4.11
go-plus, v3.3.6
language-puppet, v0.11.0
linter, v0.12.0
linter-clang, v2.25.1
linter-csslint, v0.0.11
linter-erb, v0.1.0
linter-flake8, v1.3.0
linter-flow, v0.1.4
linter-js-yaml, v1.0.0
linter-jsxhint, v0.1.1
linter-pep8, v0.1.0
linter-php, v0.0.12
linter-puppet-lint, v0.2.8
linter-pyflakes, v0.0.4
linter-shellcheck, v0.0.7
linter-tidy, v1.0.0
react, v0.11.2
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by klynton** [comment]
Closed and re-opened Atom and it loaded fine this time.
